build:
  version: '1.0'

loan:
  message: "Welcome to EazyBank loan related production APIs "
  contactDetails:
    name: "Dimuth Perera - Devops"
    email: "dimuth@eazybank.com"
  onCallSupport:
    - (777) 555-1234
    - (777) 523-1345