build:
  version: '2.0'

loan:
  message: "Welcome to EazyBank loan related QA APIs "
  contactDetails:
    name: "Nipuni Perera - QA Lead"
    email: "nipuni@eazybank.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345